MODEL:
  TYPE: regnet
  NUM_CLASSES: 10
REGNET:
  STEM_TYPE: res_stem_cifar
  SE_ON: True
  STEM_W: 16
  DEPTH: 12
  W0: 96
  WA: 19.5
  WM: 2.942
  GROUP_W: 8
OPTIM:
  BASE_LR: 0.01
  LR_POLICY: les
  VERSION: 1
  OPTIMIZER: vanilla_sgd
  MAX_EPOCH: 50
  ### these following three parameters are not used when lr_policy is les
  MOMENTUM: 0.9
  NESTEROV: False
  WARMUP_EPOCHS: 5
  ###
  WEIGHT_DECAY: 0.0005
  EMA_ALPHA: 0.00025
  EMA_UPDATE_PERIOD: 32
BN:
  USE_CUSTOM_WEIGHT_DECAY: True
TRAIN:
  DATASET: cifar10
  SPLIT: train
  BATCH_SIZE: 1024
  IM_SIZE: 32
  MIXED_PRECISION: False # les lr_policy might need higher precision
  LABEL_SMOOTHING: 0.1
  MIXUP_ALPHA: 0.5
TEST:
  DATASET: cifar10
  SPLIT: test
  BATCH_SIZE: 1000
  IM_SIZE: 32
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
LOG_PERIOD: 25
VERBOSE: False
